# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4dd77f4aaa497fcb8dc3d665798be34c3391d2f682bdb7dbe29598c0729d2faabc7a22ff01f97d1876ee26a034a1daec7267eeba5585d3d03d686d41ebe2bde7

test:
  secret_key_base: c1b27fc2995a3372f9b5d98ef90fa4b66d308ba8a8b9e1fe05036d7ccbf741de30e4829918ade00597fe89f42f0f9c9ae125ac3161ba031ce8881b5b27d9e074

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: 83fd37028019cd2a402d6840acf0ec100c0521216e163b9eb911e87089b939534b4016fc98148c212b9ff24af23326fa409a06c44fc13bfa7c7da93cd17a14eb
